### ISSUE TITLE
core.cache sessions may have a performance impact

### ISSUE THREAD

**Issue by yogthos** [boechat107/ring-ttl-session#2]
[This thread](https://www.reddit.com/r/programming/comments/3ju6fy/real_time_chat_using_spring_websocket_and/cusondq) indicates that core.cache may be causing a significant performance hit. Might be worth investigating.

**Comment by boechat107** [comment]
Thanks, @yogthos. I'll use [criterium](https://github.com/hugoduncan/criterium) to generate some benchmarks. Perhaps I should have taken [this](https://github.com/clojure/core.cache/wiki/TTL#disadvantages-to-using-an-ttl-cache) as a very serious warning. I'll investigate it better.

**Comment by boechat107** [comment]
I have created a [namespace](https://github.com/boechat107/ring-ttl-session/blob/develop/test/ring_ttl_session/performance.clj) for performance comparison with the ring's default in-memory implementation. In summary, in the current version (`0.1.1`) read operations are ~40 times slower; write operations,  ~300 times slower.

Looking at `core.cache`'s code and running the VisualVM's profiler, I guess that it's possible to improve the performance by doing some small changes. I'm planning to do it very soon.

Anyway, of course that we should expect some overhead for the TTL session when comparing to the ring's default in-memory implementation.

**Comment by yogthos** [comment]
Yeah, I think some overhead is definitely to be expected, but would be nice if it could be within an order of magnitude at least. :) Otherwise, running a thread to do session cleanup is probably cheaper overall.

**Comment by yogthos** [comment]
Another idea might be to compare performance using Java cache libs like [Guava cache](https://github.com/google/guava/wiki/CachesExplained).

**Comment by yogthos** [comment]
I made a project wrapping [expiringmap](https://github.com/jhalterman/expiringmap) Java lib [here](https://github.com/yogthos/expiring-map). It should be trivial to swap in for core.cache and see if it performs better.

**Comment by boechat107** [comment]
Thanks, @yogthos! I'll compare the performance using your lib today.

I agree with you. In the worst case, providing an implementation that uses an additional thread for session cleanup could be a good alternative.

**Comment by boechat107** [comment]
By my last tests, [expiring-map](https://github.com/yogthos/expiring-map) can be at most ~2x slower than the bare in-memory store in the worst case, which is a huge improvement over `core.cache`.

`expiring-map` became the default implementation.
